#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model AIOSStability.Components.PSATGeneratorTGOV6
 Dymola Version 2019 FD01 (64-bit), 2018-10-10 translated this at Tue Jun  2 17:54:20 2020

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
DYMOLA_STATIC double   Modelica_Math_atan3(double  u10_0, double  u20_0, double 
   y00_0);
/* Codes used in model */

/* Flattened Modelica model:

function Modelica.Math.atan3
discrete input Real u1;
discrete input Real u2;
discrete input Real y0(start = 0, unit = "rad", displayUnit = "deg") "y shall be in the range: -pi < y-y0 <= pi";
discrete output Real y(unit = "rad", displayUnit = "deg");
protected 
constant Real pi2 = 6.283185307179586;
discrete Real w;
public 
algorithm 
w := atan2(u1, u2);
if (y0 == 0) then 
y := w;
else
y := w+pi2*integer((3.141592653589793+y0-w)/pi2);
end if;
end Modelica.Math.atan3;

  */
DYMOLA_STATIC double   Modelica_Math_atan3(double  u10_0, double  u20_0, double 
   y00_0) {
  PushContext("Modelica.Math.atan3")
  {
    /* Declare outputs and temporaries */
    double   y0_0;
    double   pi20_0;
    double   w0_0;
    y0_0=0;
    pi20_0 = 6.283185307179586;
    w0_0=0;
    /* Start of real code */
      w0_0 = atan2(u10_0, u20_0);
      if (y00_0 == 0) {
        y0_0 = w0_0;
      }
      else{
        y0_0 = w0_0+pi20_0*real2integer(divmacro(3.141592653589793+y00_0-w0_0,
          "3.141592653589793+y0-w",pi20_0,"pi2"));
      }
    /* Output section */
    PopContext()
    return y0_0;
  }}
/* DSblock C-code: */

BreakSectionFunctionDef(1)
BreakSectionFunctionDef(0)
#define NX_    14
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    139
#define NP_    47
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -601833281
#define NHash2_ -485520236
#define NHash3_ 0
#define NI_    0
#define NRelF_ 7
#define NRel_  7
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    32
#define SizePre_ 0
#define SizeEq_ 3
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 2
#define NCheckIf_ 0
#define NGlobalHelp_ 83
#define NGlobalHelpI_ 16
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="AIOSStability.Components.PSATGeneratorTGOV6";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "/home/manuelnvro/.dassaultsystemes/dymola/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[23]={6 , 3 , 1 , 6 , 12 , 4 , 2 , 7 , 10 , 11 , 2
   , 3 , 8 , 2 , 4 , 9 , 2 , 5 , 13 , 1 , 14 , 0 , 0};
DYMOLA_STATIC int QJacobianGC_[85]={
1 , 1 , 0 , 1 , 0 , 6 , 6 , 6 , 0 , 6 , 1 , 12 , 1 , 12 , 2 , 2 , 0 , 2 , 0 , 10
   , 7 , 7 , 10 , 7 , 11 , 0 , 11 , 0 , 3 , 0 , 3 , 3 , 0 , 0 , 0 , 8 , 0 , 8 , 0
   , 0 , 0 , 0 , 4 , 0 , 9 , 4 , 9 , 0 , 0 , 0 , 0 , 9 , 9 , 9 , 9 , 9 , 5 , 0
   , 13 , 5 , 13 , 0 , 0 , 0 , 0 , 13 , 0 , 0 , 13 , 0 , 0 , 0 , 14 , 0 , 14 , 0
   , 0 , 0 , 0 , 14 , 0 , 0 , 0 , 14 , 0};
DYMOLA_STATIC double QJacobianCD_[15]={0  , 44 , 50 , 54 , 56 , 56 , 99 , 100 , 99
   , 96 , 130 , 140 , 165 , 112 , 102};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,23) = 2;
DYNX(W_,24) = 1;
DYNX(W_,19) = 4;
DYNX(W_,25) = 1;
DYNX(W_,26) = 0.0;
DYNX(W_,28) = 0.0;
DYNX(W_,34) = 2;
DYNX(W_,40) = 2;
DYNX(W_,69) = 3;
DYNX(W_,70) = true;
DYNX(W_,71) = true;
DYNX(W_,74) = 1;
DYNX(W_,75) = 0;
DYNX(W_,92) = 0;
DYNX(W_,50) = 0.0;
DYNX(W_,49) = 0.0;
DYNX(W_,56) = 0.0;
DYNX(W_,57) = 0.0;
DYNX(W_,51) = 0.0;
DYNX(W_,52) = 0.0;
DYNX(W_,95) = 0.0;
DYNX(W_,96) = 0.0;
DYNX(W_,94) = 0.0;
DYNX(W_,93) = 0.0;
DYNX(W_,3) = 0.0;
DYNX(W_,2) = 0.0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(W_,7) = DYNX(DP_,3);
DYNX(W_,17) = DYNX(DP_,15);
DYNX(W_,18) = DYNX(DP_,14);
DYNX(W_,27) = DYNX(DP_,19);
DYNX(DYNhelp,0) = sqrtGuarded(DYNX(W_,17)*DYNX(W_,17)+DYNX(W_,18)*DYNX(W_,18),
  "avr2.ExcitationSystem.a[1]*avr2.ExcitationSystem.a[1]+avr2.ExcitationSystem.a[2]*avr2.ExcitationSystem.a[2]");
DYNX(W_,29) = IF DYNX(W_,18) > 1E-13*DYNX(DYNhelp,0) THEN DYNX(W_,18) ELSE 1.0;
DYNX(W_,30) = DYNX(DP_,17);
DYNX(W_,31) = DYNX(DP_,18);
DYNX(W_,32) = DYNX(DP_,12);
DYNX(W_,33) = DYNX(DP_,13);
DYNX(DYNhelp,1) = fabs(DYNX(W_,32));
DYNX(W_,37) = DYNX(DYNhelp,1) < 1E-15;
DYNX(W_,39) = DYNX(DP_,16);
DYNX(W_,41) = DYNX(W_,7);
DYNX(W_,43) = DYNX(DP_,10);
DYNX(W_,44) = DYNX(DP_,11);
DYNX(W_,46) = DYNX(DP_,9);
DYNX(W_,47) = DYNX(DP_,8);
DYNX(W_,48) = IF DYNX(W_,44) < 1E-15 THEN 1000 ELSE DYNX(W_,44);
DYNX(W_,91) = DYNX(DP_,2);
DYNX(W_,61) = DYNX(W_,91);
DYNX(W_,90) = DYNX(DP_,7);
DYNX(W_,60) = DYNX(W_,90);
DYNX(W_,62) = DYNX(DP_,2);
DYNX(W_,63) = divmacro(DYNX(DP_,0)*sqr(DYNX(W_,61)),"SysData.S_b*oel.Vn^2",
  DYNX(W_,60)*sqr(DYNX(W_,62)),"oel.Sn*oel.V_b^2");
DYNX(W_,58) = DYNX(DP_,37);
DYNX(W_,54) = DYNX(W_,63)*DYNX(W_,58);
DYNX(W_,59) = DYNX(DP_,38);
DYNX(W_,55) = DYNX(W_,63)*DYNX(W_,59);
DYNX(W_,64) = divmacro(DYNX(W_,60)*DYNX(W_,62),"oel.Sn*oel.V_b",DYNX(DP_,0)*
  DYNX(W_,61),"SysData.S_b*oel.Vn");
DYNX(W_,66) = DYNX(DP_,23);
DYNX(W_,67) = divmacro(1,"1",DYNX(DP_,22),"oel.T0");
DYNX(W_,68) = DYNX(DP_,24);
DYNX(W_,82) = divmacro(DYNX(DP_,5),"P_0",DYNX(DP_,7),"M_b");
DYNX(W_,73) = DYNX(W_,82);
DYNX(W_,77) = DYNX(W_,73);
DYNX(W_,78) = DYNX(W_,77);
DYNX(W_,79) = (1-divmacro(DYNX(DP_,31),"tGTypeI.T3",DYNX(DP_,30),"tGTypeI.Tc"))*
  DYNX(W_,78);
DYNX(W_,80) = (1-divmacro(DYNX(DP_,32),"tGTypeI.T4",DYNX(DP_,33),"tGTypeI.T5"))*
  (DYNX(W_,79)+divmacro(DYNX(DP_,31)*DYNX(W_,78),"tGTypeI.T3*tGTypeI.xg10",
  DYNX(DP_,30),"tGTypeI.Tc"));
DYNX(W_,83) = DYNX(DP_,2);
DYNX(W_,84) = DYNX(DP_,3);
DYNX(W_,85) = DYNX(DP_,4);
DYNX(W_,86) = DYNX(DP_,5);
DYNX(W_,87) = DYNX(DP_,6);
DYNX(W_,88) = DYNX(DP_,0);
DYNX(W_,89) = DYNX(DP_,1);
DYNX(W_,104) = 6.283185307179586*DYNX(W_,89);
DYNX(W_,105) = divmacro(DYNX(W_,88),"order6_1.S_b",DYNX(W_,90),"order6_1.Sn");
DYNX(W_,106) = divmacro(DYNX(W_,90)*DYNX(W_,83),"order6_1.Sn*order6_1.V_b",
  DYNX(W_,88)*DYNX(W_,91),"order6_1.S_b*order6_1.Vn");
DYNX(W_,107) = divmacro(DYNX(W_,91),"order6_1.Vn",DYNX(W_,83),"order6_1.V_b");
DYNX(W_,108) = divmacro(DYNX(W_,88)*sqr(DYNX(W_,91)),"order6_1.S_b*order6_1.Vn^2",
  DYNX(W_,90)*sqr(DYNX(W_,83)),"order6_1.Sn*order6_1.V_b^2");
DYNX(W_,109) = divmacro(DYNX(W_,86),"order6_1.P_0",DYNX(W_,88),"order6_1.S_b");
DYNX(W_,110) = divmacro(DYNX(W_,87),"order6_1.Q_0",DYNX(W_,88),"order6_1.S_b");
DYNX(DYNhelp,2) = cos(0.017453292519943295*DYNX(W_,85));
DYNX(W_,111) = DYNX(W_,84)*DYNX(DYNhelp,2);
DYNX(DYNhelp,3) = sin(0.017453292519943295*DYNX(W_,85));
DYNX(W_,112) = DYNX(W_,84)*DYNX(DYNhelp,3);
DYNX(W_,113) = DYNX(W_,109);
DYNX(W_,114) =  -DYNX(W_,110);
DYNX(W_,115) = divmacro(DYNX(W_,113)*DYNX(W_,111)-DYNX(W_,114)*DYNX(W_,112),
  "order6_1.S0.re*order6_1.Vt0.re-order6_1.S0.im*order6_1.Vt0.im",DYNX(W_,111)*
  DYNX(W_,111)+DYNX(W_,112)*DYNX(W_,112),"order6_1.Vt0.re*order6_1.Vt0.re+order6_1.Vt0.im*order6_1.Vt0.im");
DYNX(W_,116) = divmacro(DYNX(W_,113)*DYNX(W_,112)+DYNX(W_,114)*DYNX(W_,111),
  "order6_1.S0.re*order6_1.Vt0.im+order6_1.S0.im*order6_1.Vt0.re",DYNX(W_,111)*
  DYNX(W_,111)+DYNX(W_,112)*DYNX(W_,112),"order6_1.Vt0.re*order6_1.Vt0.re+order6_1.Vt0.im*order6_1.Vt0.im");
DYNX(W_,117) = DYNX(W_,111);
DYNX(W_,118) = DYNX(W_,112);
DYNX(W_,119) =  -DYNX(W_,115);
DYNX(W_,120) =  -DYNX(W_,116);
DYNX(W_,121) = DYNX(DP_,38);
DYNX(DYNhelp,4) = DYNX(DP_,34)*DYNX(W_,108);
DYNX(DYNhelp,5) = DYNX(W_,121)*DYNX(W_,108);
DYNX(W_,122) = (PushModelContext(1,"Modelica.Math.atan3(order6_1.Vt0.im+order6_1.ra*order6_1.Z_MBtoSB*order6_1.I0.im+order6_1.xq0*order6_1.Z_MBtoSB*order6_1.I0.re, order6_1.Vt0.re+order6_1.ra*order6_1.Z_MBtoSB*order6_1.I0.re-order6_1.xq0*order6_1.Z_MBtoSB*order6_1.I0.im, 0)")
  Modelica_Math_atan3(DYNX(W_,112)+DYNX(DYNhelp,4)*DYNX(W_,116)+DYNX(DYNhelp,5)*
  DYNX(W_,115), DYNX(W_,111)+DYNX(DYNhelp,4)*DYNX(W_,115)-DYNX(DYNhelp,5)*
  DYNX(W_,116), 0));
PopModelContext();
DYNX(DYNhelp,6) = 1.5707963267948966-DYNX(W_,122);
DYNX(DYNhelp,7) = cos(DYNX(DYNhelp,6));
DYNX(DYNhelp,8) = sin(DYNX(DYNhelp,6));
DYNX(DYNhelp,9) = divmacro(1.0,"1.0",DYNX(W_,107),"order6_1.V_MBtoSB");
DYNX(W_,123) = DYNX(DYNhelp,9)*(DYNX(W_,111)*DYNX(DYNhelp,7)-DYNX(W_,112)*
  DYNX(DYNhelp,8));
DYNX(DYNhelp,10) = 1.5707963267948966-DYNX(W_,122);
DYNX(DYNhelp,11) = divmacro(1.0,"1.0",DYNX(W_,107),"order6_1.V_MBtoSB");
DYNX(W_,124) = DYNX(DYNhelp,11)*(DYNX(W_,111)*DYNX(DYNhelp,8)+DYNX(W_,112)*
  DYNX(DYNhelp,7));
DYNX(DYNhelp,12) = 1.5707963267948966-DYNX(W_,122);
DYNX(DYNhelp,13) = divmacro(1.0,"1.0",DYNX(W_,106),"order6_1.I_MBtoSB");
DYNX(W_,125) = DYNX(DYNhelp,13)*(DYNX(W_,115)*DYNX(DYNhelp,7)-DYNX(W_,116)*
  DYNX(DYNhelp,8));
DYNX(DYNhelp,14) = 1.5707963267948966-DYNX(W_,122);
DYNX(DYNhelp,15) = divmacro(1.0,"1.0",DYNX(W_,106),"order6_1.I_MBtoSB");
DYNX(W_,126) = DYNX(DYNhelp,15)*(DYNX(W_,115)*DYNX(DYNhelp,8)+DYNX(W_,116)*
  DYNX(DYNhelp,7));
DYNX(W_,127) = DYNX(W_,123);
DYNX(W_,128) = DYNX(W_,124);
DYNX(W_,129) = DYNX(W_,125);
DYNX(W_,130) = DYNX(W_,126);
DYNX(W_,131) = divmacro((DYNX(W_,128)+DYNX(DP_,34)*DYNX(W_,130))*DYNX(W_,130)+(
  DYNX(W_,127)+DYNX(DP_,34)*DYNX(W_,129))*DYNX(W_,129),"(order6_1.vq0+order6_1.ra*order6_1.iq0)*order6_1.iq0+(order6_1.vd0+order6_1.ra*order6_1.id0)*order6_1.id0",
  DYNX(W_,105),"order6_1.S_SBtoMB");
DYNX(W_,132) = DYNX(W_,128)+DYNX(DP_,34)*DYNX(W_,130)+DYNX(DP_,40)*DYNX(W_,129);
DYNX(W_,133) = DYNX(W_,127)+DYNX(DP_,34)*DYNX(W_,129)-DYNX(DP_,41)*DYNX(W_,130);
DYNX(W_,134) = (DYNX(DP_,38)-DYNX(DP_,39)-divmacro(DYNX(DP_,45)*DYNX(DP_,41)*(
  DYNX(DP_,38)-DYNX(DP_,39)),"order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)",
  DYNX(DP_,43)*DYNX(DP_,39),"order6_1.T1q0*order6_1.x1q"))*DYNX(W_,130);
DYNX(W_,135) = DYNX(DP_,37)-DYNX(DP_,35)-divmacro(DYNX(DP_,44)*DYNX(DP_,40)*(
  DYNX(DP_,37)-DYNX(DP_,35)),"order6_1.T2d0*order6_1.x2d*(order6_1.xd-order6_1.x1d)",
  DYNX(DP_,42)*DYNX(DP_,35),"order6_1.T1d0*order6_1.x1d");
DYNX(W_,136) = DYNX(DP_,35)-DYNX(DP_,40)+divmacro(DYNX(DP_,44)*DYNX(DP_,40)*(
  DYNX(DP_,37)-DYNX(DP_,35)),"order6_1.T2d0*order6_1.x2d*(order6_1.xd-order6_1.x1d)",
  DYNX(DP_,42)*DYNX(DP_,35),"order6_1.T1d0*order6_1.x1d");
DYNX(W_,137) = DYNX(W_,132)+DYNX(W_,136)*DYNX(W_,129)-divmacro(DYNX(DP_,46)*((
  DYNX(W_,135)+DYNX(W_,136))*DYNX(W_,129)+DYNX(W_,132)),"order6_1.Taa*((order6_1.K1+order6_1.K2)*order6_1.id0+order6_1.e2q0)",
  DYNX(DP_,42),"order6_1.T1d0");
DYNX(W_,138) = divmacro(DYNX(W_,107)*(DYNX(W_,135)*DYNX(W_,129)+DYNX(W_,137)),
  "order6_1.V_MBtoSB*(order6_1.K1*order6_1.id0+order6_1.e1q0)",1-divmacro(
  DYNX(DP_,46),"order6_1.Taa",DYNX(DP_,42),"order6_1.T1d0"),"1-order6_1.Taa/order6_1.T1d0");
BoundParameterConstantSection
DYNX(W_,13) = DYNX(W_,138);
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,0) = DYNX(W_,117);
DYNX(W_,1) = DYNX(W_,118);
DYNX(W_,4) = DYNX(W_,84);
DYNX(W_,5) = DYNX(W_,138);
DYNX(W_,14) = DYNX(W_,45);
DYNX(W_,22) = DYNX(W_,20);
DYNX(W_,72) = DYNX(W_,131);
DYNX(W_,97) = 0.017453292519943295*DYNX(W_,85);
DYNX(W_,98) = DYNX(W_,127);
DYNX(W_,99) = DYNX(W_,128);
DYNX(W_,100) = DYNX(W_,129);
DYNX(W_,101) = DYNX(W_,130);
DYNX(W_,102) = DYNX(W_,131);
DYNX(X_,1) = DYNX(W_,35);
DYNX(X_,2) = DYNX(W_,41);
DYNX(X_,4) = DYNX(DP_,26);
DYNX(X_,5) = DYNX(W_,78);
DYNX(X_,6) = DYNX(W_,79);
DYNX(X_,7) = DYNX(W_,80);
DYNX(X_,8) = DYNX(W_,122);
DYNX(X_,10) = DYNX(W_,137);
DYNX(X_,11) = DYNX(W_,134);
DYNX(X_,12) = DYNX(W_,132);
DYNX(X_,13) = DYNX(W_,133);
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(F_,2) = 0;
DYNX(F_,11) = 0;
DYNX(F_,13) = 0;
DYNX(F_,8) = 0.0;
DYNX(F_,1) = 0;
DYNX(X_,9) = 1;
DYNX(W_,7) = DYNX(DP_,3);
DYNX(W_,91) = DYNX(DP_,2);
DYNX(W_,83) = DYNX(DP_,2);
DYNX(W_,107) = divmacro(DYNX(W_,91),"order6_1.Vn",DYNX(W_,83),"order6_1.V_b");
DYNX(W_,135) = DYNX(DP_,37)-DYNX(DP_,35)-divmacro(DYNX(DP_,44)*DYNX(DP_,40)*(
  DYNX(DP_,37)-DYNX(DP_,35)),"order6_1.T2d0*order6_1.x2d*(order6_1.xd-order6_1.x1d)",
  DYNX(DP_,42)*DYNX(DP_,35),"order6_1.T1d0*order6_1.x1d");
DYNX(W_,86) = DYNX(DP_,5);
DYNX(W_,88) = DYNX(DP_,0);
DYNX(W_,109) = divmacro(DYNX(W_,86),"order6_1.P_0",DYNX(W_,88),"order6_1.S_b");
DYNX(W_,113) = DYNX(W_,109);
DYNX(W_,84) = DYNX(DP_,3);
DYNX(W_,85) = DYNX(DP_,4);
DYNX(W_,111) = DYNX(W_,84)*cos(0.017453292519943295*DYNX(W_,85));
DYNX(W_,87) = DYNX(DP_,6);
DYNX(W_,110) = divmacro(DYNX(W_,87),"order6_1.Q_0",DYNX(W_,88),"order6_1.S_b");
DYNX(W_,114) =  -DYNX(W_,110);
DYNX(W_,112) = DYNX(W_,84)*sin(0.017453292519943295*DYNX(W_,85));
DYNX(W_,115) = divmacro(DYNX(W_,113)*DYNX(W_,111)-DYNX(W_,114)*DYNX(W_,112),
  "order6_1.S0.re*order6_1.Vt0.re-order6_1.S0.im*order6_1.Vt0.im",DYNX(W_,111)*
  DYNX(W_,111)+DYNX(W_,112)*DYNX(W_,112),"order6_1.Vt0.re*order6_1.Vt0.re+order6_1.Vt0.im*order6_1.Vt0.im");
DYNX(W_,90) = DYNX(DP_,7);
DYNX(W_,108) = divmacro(DYNX(W_,88)*sqr(DYNX(W_,91)),"order6_1.S_b*order6_1.Vn^2",
  DYNX(W_,90)*sqr(DYNX(W_,83)),"order6_1.Sn*order6_1.V_b^2");
DYNX(W_,116) = divmacro(DYNX(W_,113)*DYNX(W_,112)+DYNX(W_,114)*DYNX(W_,111),
  "order6_1.S0.re*order6_1.Vt0.im+order6_1.S0.im*order6_1.Vt0.re",DYNX(W_,111)*
  DYNX(W_,111)+DYNX(W_,112)*DYNX(W_,112),"order6_1.Vt0.re*order6_1.Vt0.re+order6_1.Vt0.im*order6_1.Vt0.im");
DYNX(W_,121) = DYNX(DP_,38);
DYNX(W_,122) = (PushModelContext(1,"Modelica.Math.atan3(order6_1.Vt0.im+order6_1.ra*order6_1.Z_MBtoSB*order6_1.I0.im+order6_1.xq0*order6_1.Z_MBtoSB*order6_1.I0.re, order6_1.Vt0.re+order6_1.ra*order6_1.Z_MBtoSB*order6_1.I0.re-order6_1.xq0*order6_1.Z_MBtoSB*order6_1.I0.im, 0)")
  Modelica_Math_atan3(DYNX(W_,112)+DYNX(DP_,34)*DYNX(W_,108)*DYNX(W_,116)+
  DYNX(W_,121)*DYNX(W_,108)*DYNX(W_,115), DYNX(W_,111)+DYNX(DP_,34)*DYNX(W_,108)
  *DYNX(W_,115)-DYNX(W_,121)*DYNX(W_,108)*DYNX(W_,116), 0));
PopModelContext();
DYNX(W_,106) = divmacro(DYNX(W_,90)*DYNX(W_,83),"order6_1.Sn*order6_1.V_b",
  DYNX(W_,88)*DYNX(W_,91),"order6_1.S_b*order6_1.Vn");
DYNX(W_,125) = divmacro(DYNX(W_,115)*cos(1.5707963267948966-DYNX(W_,122))-
  DYNX(W_,116)*sin(1.5707963267948966-DYNX(W_,122)),"order6_1.I0.re*cos(1.5707963267948966-order6_1.delta0)-order6_1.I0.im*sin(1.5707963267948966-order6_1.delta0)",
  DYNX(W_,106),"order6_1.I_MBtoSB");
DYNX(W_,129) = DYNX(W_,125);
DYNX(W_,124) = divmacro(DYNX(W_,111)*sin(1.5707963267948966-DYNX(W_,122))+
  DYNX(W_,112)*cos(1.5707963267948966-DYNX(W_,122)),"order6_1.Vt0.re*sin(1.5707963267948966-order6_1.delta0)+order6_1.Vt0.im*cos(1.5707963267948966-order6_1.delta0)",
  DYNX(W_,107),"order6_1.V_MBtoSB");
DYNX(W_,128) = DYNX(W_,124);
DYNX(W_,126) = divmacro(DYNX(W_,115)*sin(1.5707963267948966-DYNX(W_,122))+
  DYNX(W_,116)*cos(1.5707963267948966-DYNX(W_,122)),"order6_1.I0.re*sin(1.5707963267948966-order6_1.delta0)+order6_1.I0.im*cos(1.5707963267948966-order6_1.delta0)",
  DYNX(W_,106),"order6_1.I_MBtoSB");
DYNX(W_,130) = DYNX(W_,126);
DYNX(W_,132) = DYNX(W_,128)+DYNX(DP_,34)*DYNX(W_,130)+DYNX(DP_,40)*DYNX(W_,129);
DYNX(W_,136) = DYNX(DP_,35)-DYNX(DP_,40)+divmacro(DYNX(DP_,44)*DYNX(DP_,40)*(
  DYNX(DP_,37)-DYNX(DP_,35)),"order6_1.T2d0*order6_1.x2d*(order6_1.xd-order6_1.x1d)",
  DYNX(DP_,42)*DYNX(DP_,35),"order6_1.T1d0*order6_1.x1d");
DYNX(W_,137) = DYNX(W_,132)+DYNX(W_,136)*DYNX(W_,129)-divmacro(DYNX(DP_,46)*((
  DYNX(W_,135)+DYNX(W_,136))*DYNX(W_,129)+DYNX(W_,132)),"order6_1.Taa*((order6_1.K1+order6_1.K2)*order6_1.id0+order6_1.e2q0)",
  DYNX(DP_,42),"order6_1.T1d0");
DYNX(W_,138) = divmacro(DYNX(W_,107)*(DYNX(W_,135)*DYNX(W_,129)+DYNX(W_,137)),
  "order6_1.V_MBtoSB*(order6_1.K1*order6_1.id0+order6_1.e1q0)",1-divmacro(
  DYNX(DP_,46),"order6_1.Taa",DYNX(DP_,42),"order6_1.T1d0"),"1-order6_1.Taa/order6_1.T1d0");
DYNX(W_,13) = DYNX(W_,138);
  DYNX(W_,9) = DYNX(W_,13);
DYNX(W_,10) = DYNX(DP_,14)*DYNX(W_,9)+DYNX(DP_,17)*exp(DYNX(DP_,18)*fabs(
  DYNX(W_,9)))*DYNX(W_,9);
DYNX(W_,8) = DYNX(W_,10)-DYNX(DP_,17)*exp(DYNX(DP_,18)*fabs(DYNX(W_,9)))*
  DYNX(W_,9);
DYNX(W_,11) =  -divmacro(DYNX(W_,9)*DYNX(DP_,12),"avr2.vf00*avr2.Kf",
  DYNX(DP_,13),"avr2.Tf");
DYNX(W_,17) = DYNX(DP_,15);
DYNX(W_,18) = DYNX(DP_,14);
DYNX(W_,20) = DYNX(W_,8);
DYNX(W_,21) = DYNX(W_,9);
DYNX(W_,27) = DYNX(DP_,19);
DYNX(W_,29) = IF DYNX(W_,18) > 1E-13*sqrtGuarded(DYNX(W_,17)*DYNX(W_,17)+
  DYNX(W_,18)*DYNX(W_,18),"avr2.ExcitationSystem.a[1]*avr2.ExcitationSystem.a[1]+avr2.ExcitationSystem.a[2]*avr2.ExcitationSystem.a[2]")
   THEN DYNX(W_,18) ELSE 1.0;
DYNX(W_,30) = DYNX(DP_,17);
DYNX(W_,31) = DYNX(DP_,18);
DYNX(W_,32) = DYNX(DP_,12);
DYNX(W_,33) = DYNX(DP_,13);
DYNX(W_,35) = DYNX(W_,9);
DYNX(W_,39) = DYNX(DP_,16);
DYNX(W_,41) = DYNX(W_,7);
DYNX(W_,43) = DYNX(DP_,10);
DYNX(W_,44) = DYNX(DP_,11);
DYNX(W_,45) = DYNX(W_,10);
DYNX(W_,46) = DYNX(DP_,9);
DYNX(W_,47) = DYNX(DP_,8);
DYNX(W_,48) = IF DYNX(W_,44) < 1E-15 THEN 1000 ELSE DYNX(W_,44);
DYNX(W_,61) = DYNX(W_,91);
DYNX(W_,60) = DYNX(W_,90);
DYNX(W_,62) = DYNX(DP_,2);
DYNX(W_,63) = divmacro(DYNX(DP_,0)*sqr(DYNX(W_,61)),"SysData.S_b*oel.Vn^2",
  DYNX(W_,60)*sqr(DYNX(W_,62)),"oel.Sn*oel.V_b^2");
DYNX(W_,58) = DYNX(DP_,37);
DYNX(W_,54) = DYNX(W_,63)*DYNX(W_,58);
DYNX(W_,59) = DYNX(DP_,38);
DYNX(W_,55) = DYNX(W_,63)*DYNX(W_,59);
DYNX(W_,64) = divmacro(DYNX(W_,60)*DYNX(W_,62),"oel.Sn*oel.V_b",DYNX(DP_,0)*
  DYNX(W_,61),"SysData.S_b*oel.Vn");
DYNX(W_,66) = DYNX(DP_,23);
DYNX(W_,67) = divmacro(1,"1",DYNX(DP_,22),"oel.T0");
DYNX(W_,68) = DYNX(DP_,24);
DYNX(W_,82) = divmacro(DYNX(DP_,5),"P_0",DYNX(DP_,7),"M_b");
DYNX(W_,73) = DYNX(W_,82);
DYNX(W_,77) = DYNX(W_,73);
DYNX(W_,78) = DYNX(W_,77);
DYNX(W_,79) = (1-divmacro(DYNX(DP_,31),"tGTypeI.T3",DYNX(DP_,30),"tGTypeI.Tc"))*
  DYNX(W_,78);
DYNX(W_,80) = (1-divmacro(DYNX(DP_,32),"tGTypeI.T4",DYNX(DP_,33),"tGTypeI.T5"))*
  (DYNX(W_,79)+divmacro(DYNX(DP_,31)*DYNX(W_,78),"tGTypeI.T3*tGTypeI.xg10",
  DYNX(DP_,30),"tGTypeI.Tc"));
DYNX(W_,89) = DYNX(DP_,1);
DYNX(W_,104) = 6.283185307179586*DYNX(W_,89);
DYNX(W_,105) = divmacro(DYNX(W_,88),"order6_1.S_b",DYNX(W_,90),"order6_1.Sn");
DYNX(W_,117) = DYNX(W_,111);
DYNX(W_,118) = DYNX(W_,112);
DYNX(W_,119) =  -DYNX(W_,115);
DYNX(W_,120) =  -DYNX(W_,116);
DYNX(W_,123) = divmacro(DYNX(W_,111)*cos(1.5707963267948966-DYNX(W_,122))-
  DYNX(W_,112)*sin(1.5707963267948966-DYNX(W_,122)),"order6_1.Vt0.re*cos(1.5707963267948966-order6_1.delta0)-order6_1.Vt0.im*sin(1.5707963267948966-order6_1.delta0)",
  DYNX(W_,107),"order6_1.V_MBtoSB");
DYNX(W_,127) = DYNX(W_,123);
DYNX(W_,131) = divmacro((DYNX(W_,128)+DYNX(DP_,34)*DYNX(W_,130))*DYNX(W_,130)+(
  DYNX(W_,127)+DYNX(DP_,34)*DYNX(W_,129))*DYNX(W_,129),"(order6_1.vq0+order6_1.ra*order6_1.iq0)*order6_1.iq0+(order6_1.vd0+order6_1.ra*order6_1.id0)*order6_1.id0",
  DYNX(W_,105),"order6_1.S_SBtoMB");
DYNX(W_,133) = DYNX(W_,127)+DYNX(DP_,34)*DYNX(W_,129)-DYNX(DP_,41)*DYNX(W_,130);
DYNX(W_,134) = (DYNX(DP_,38)-DYNX(DP_,39)-divmacro(DYNX(DP_,45)*DYNX(DP_,41)*(
  DYNX(DP_,38)-DYNX(DP_,39)),"order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)",
  DYNX(DP_,43)*DYNX(DP_,39),"order6_1.T1q0*order6_1.x1q"))*DYNX(W_,130);
DYNX(W_,37) = fabs(DYNX(W_,32)) < 1E-15;
  DYNX(W_,12) = DYNX(W_,7)+divmacro(DYNX(W_,10),"avr2.vr10",DYNX(DP_,10),
    "avr2.Ka");
DYNX(X_,3) = DYNX(W_,45);
DYNX(X_,8) = DYNX(W_,122);

 /* Linear system of equations to solve. */
/* Tag: initialization.linear[1] */
/* Introducing 2 common subexpressions used in 2 expressions */
/* Of the common subexpressions 2 are reals, 0 are integers, and 0
   are booleans. */
{
  const char*const varnames_[]={"order6_1.id", "order6_1.iq"};
  const double nominal_[]={1, 1};
  DidLinearSystemOfEquations(J, b, y, 2, DYNX(DYNhelp,16), 24, DYNX(did_->helpvari_vec,0), 8);
  /* Jacobian depending on continuous variables */
  SetNeedFactor(J);
  if (NeedFactor(J)) {
    MatrixZeros(J);
    DYNX(DYNhelp,40) =  -DYNX(W_,106)*sin(DYNX(X_,8));
    DYNX(DYNhelp,41) = DYNX(W_,106)*cos(DYNX(X_,8));
    SetMatrixLeading(J, 1, 1, 2, DYNX(DYNhelp,40));
    SetMatrixLeading(J, 1, 2, 2,  -DYNX(DYNhelp,41));
    SetMatrixLeading(J, 2, 1, 2, DYNX(DYNhelp,41));
    SetMatrixLeading(J, 2, 2, 2, DYNX(DYNhelp,40));
  }
  SetVector(y, 1, DYNX(W_,129));
  SetVector(y, 2, DYNX(W_,130));
  SolveLinearSystemOfEquations(J, b, y, 1);
  DYNX(W_,100) = GetVector(y, 1);
  DYNX(W_,101) = GetVector(y, 2);
  EndStaticLinearSystemOfEquations(J);
}
 /* End of Equation Block */ 

 /* Linear system of equations to solve. */
/* Introducing 4 common subexpressions used in 5 expressions */
/* Of the common subexpressions 4 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,42) = divmacro(1.0,"1.0",DYNX(DP_,43),"order6_1.T1q0");
DYNX(DYNhelp,43) = DYNX(DP_,38)-DYNX(DP_,39);
DYNX(DYNhelp,44) = DYNX(DP_,45)*DYNX(DP_,41)*DYNX(DYNhelp,43);
DYNX(DYNhelp,45) = divmacro(1.0,"1.0",DYNX(DP_,39),"order6_1.x1q");
DYNX(X_,11) = DYNX(W_,134);
SolveScalarLinearParametric( -DYNX(DYNhelp,42)*(-1.0)," -(-1.0)/order6_1.T1q0", 
  DYNX(DYNhelp,42)*(DYNX(DYNhelp,43)-DYNX(DYNhelp,45)*DYNX(DYNhelp,42)*
  DYNX(DYNhelp,44))*DYNX(W_,101),"(order6_1.xq-order6_1.x1q-order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)/order6_1.T1q0/order6_1.x1q)*order6_1.iq/order6_1.T1q0",
   DYNX(X_,11),"order6_1.e1d");
 /* End of Equation Block */ 

 /* Linear system of equations to solve. */
/* Introducing 4 common subexpressions used in 4 expressions */
/* Of the common subexpressions 4 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,46) = divmacro(1.0,"1.0",DYNX(DP_,45),"order6_1.T2q0");
DYNX(DYNhelp,47) = divmacro(DYNX(DP_,45)*DYNX(DP_,41)*(DYNX(DP_,38)-DYNX(DP_,39)),
  "order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)",DYNX(DP_,43),
  "order6_1.T1q0");
DYNX(DYNhelp,48) = divmacro(1.0,"1.0",DYNX(DP_,43),"order6_1.T1q0");
DYNX(DYNhelp,49) = divmacro(1.0,"1.0",DYNX(DP_,39),"order6_1.x1q");
DYNX(X_,13) = DYNX(W_,133);
SolveScalarLinearParametric( -DYNX(DYNhelp,46)*(-1.0)," -(-1.0)/order6_1.T2q0", 
  DYNX(DYNhelp,46)*(DYNX(X_,11)+(DYNX(DP_,39)-DYNX(DP_,41)+DYNX(DYNhelp,49)*
  DYNX(DYNhelp,47))*DYNX(W_,101)),"(order6_1.e1d+(order6_1.x1q-order6_1.x2q+order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)/order6_1.T1q0/order6_1.x1q)*order6_1.iq)/order6_1.T2q0",
   DYNX(X_,13),"order6_1.e2d");
 /* End of Equation Block */ 

DYNX(X_,12) = DYNX(W_,132);
DYNX(W_,98) = DYNX(X_,13)-DYNX(DP_,34)*DYNX(W_,100)+DYNX(DP_,41)*DYNX(W_,101);
DYNX(W_,99) = DYNX(X_,12)-(DYNX(DP_,34)*DYNX(W_,101)+DYNX(DP_,40)*DYNX(W_,100));
BreakSectionFunctionCallNew(0);
BreakSectionFunctionEnd()
BreakSectionFunctionStart(1);
DYNX(W_,0) = DYNX(W_,107)*(sin(DYNX(X_,8))*DYNX(W_,98)+cos(DYNX(X_,8))*
  DYNX(W_,99));
DYNX(W_,1) = DYNX(W_,107)*(sin(DYNX(X_,8))*DYNX(W_,99)-cos(DYNX(X_,8))*
  DYNX(W_,98));
DYNX(W_,4) = sqrtGuarded(sqr(DYNX(W_,0))+sqr(DYNX(W_,1)),"pwPin.vr^2+pwPin.vi^2");
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 2 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,50) = divmacro(1.0,"1.0",DYNX(W_,39),"avr2.firstOrder2.T");
DYNX(X_,2) = DYNX(W_,41);
SolveScalarLinearParametric( -DYNX(DYNhelp,50)*(-1.0)," -(-1.0)/avr2.firstOrder2.T",
   DYNX(DYNhelp,50)*DYNX(DP_,21)*DYNX(W_,4),"avr2.firstOrder2.k*avr2.v/avr2.firstOrder2.T",
   DYNX(X_,2),"avr2.firstOrder2.y");
 /* End of Equation Block */ 

DYNX(X_,10) = DYNX(W_,137);
DYNX(X_,5) = DYNX(W_,78);
DYNX(X_,6) = DYNX(W_,79);
DYNX(X_,7) = DYNX(W_,80);
DYNX(X_,4) = DYNX(DP_,26);
DYNX(W_,5) = DYNX(W_,21);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,51) = divmacro(1.0,"1.0",DYNX(W_,29),"avr2.ExcitationSystem.a_end");
DYNX(X_,0) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,51)*DYNX(W_,27)," -avr2.ExcitationSystem.bb[2]/avr2.ExcitationSystem.a_end",
    -DYNX(W_,5)," -avr2.vf", DYNX(X_,0),"avr2.ExcitationSystem.x_scaled[1]");
 /* End of Equation Block */ 

 /* Linear system of equations to solve. */
DYNX(X_,1) = DYNX(W_,35);
SolveScalarLinearParametric( -(IF DYNX(W_,37) THEN 0 ELSE divmacro(-1.0,"-1.0",
  DYNX(W_,33),"avr2.derivativeBlock.T"))," -(if avr2.derivativeBlock.zeroGain then 0 else (-1.0)/avr2.derivativeBlock.T)",
   IF DYNX(W_,37) THEN 0 ELSE divmacro(DYNX(W_,5),"avr2.vf",DYNX(W_,33),
  "avr2.derivativeBlock.T"),"(if avr2.derivativeBlock.zeroGain then 0 else avr2.vf/avr2.derivativeBlock.T)",
   DYNX(X_,1),"avr2.derivativeBlock.x");
 /* End of Equation Block */ 

InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(W_,6) = DYNX(W_,12)-DYNX(X_,4);
DYNX(W_,38) = DYNX(W_,6)-DYNX(X_,2);
DYNX(W_,5) = divmacro(DYNX(W_,27)*DYNX(X_,0),"avr2.ExcitationSystem.bb[2]*avr2.ExcitationSystem.x_scaled[1]",
  DYNX(W_,29),"avr2.ExcitationSystem.a_end");
DYNX(W_,36) = IF DYNX(W_,37) THEN 0 ELSE divmacro(DYNX(W_,32)*(DYNX(W_,5)-
  DYNX(X_,1)),"avr2.derivativeBlock.k*(avr2.vf-avr2.derivativeBlock.x)",
  DYNX(W_,33),"avr2.derivativeBlock.T");
DYNX(W_,42) = DYNX(W_,38)-DYNX(W_,36);
 /* Linear system of equations to solve. */
DYNX(F_,3) = RememberSimple_(DYNX(F_,3), 0);
SolveScalarLinearParametric(DYNX(W_,48),"avr2.simpleLagLim.T_mod", DYNX(W_,43)*
  DYNX(W_,42)-DYNX(X_,3),"avr2.simpleLagLim.K*avr2.simpleLagLim.u-avr2.simpleLagLim.state",
   DYNX(F_,3),"der(avr2.simpleLagLim.state)");
 /* End of Equation Block */ 


 /* Linear system of equations to solve. */
/* Tag: simulation.linear[1] */
/* Introducing 4 common subexpressions used in 2 expressions */
/* Of the common subexpressions 4 are reals, 0 are integers, and 0
   are booleans. */
{
  const char*const varnames_[]={"order6_1.iq", "order6_1.id"};
  const double nominal_[]={1, 1};
  DidLinearSystemOfEquations(J, b, y, 2, DYNX(DYNhelp,52), 24, DYNX(did_->helpvari_vec,8), 8);
  /* Jacobian depending on continuous variables */
  SetNeedFactor(J);
  if (NeedFactor(J)) {
    MatrixZeros(J);
    DYNX(DYNhelp,76) = cos(DYNX(X_,8));
    DYNX(DYNhelp,77) = DYNX(W_,106)*DYNX(DYNhelp,76);
    DYNX(DYNhelp,78) = sin(DYNX(X_,8));
    DYNX(DYNhelp,79) =  -DYNX(W_,106)*DYNX(DYNhelp,78);
    SetMatrixLeading(J, 1, 1, 2,  -DYNX(DYNhelp,77));
    SetMatrixLeading(J, 1, 2, 2, DYNX(DYNhelp,79));
    SetMatrixLeading(J, 2, 1, 2, DYNX(DYNhelp,79));
    SetMatrixLeading(J, 2, 2, 2, DYNX(DYNhelp,77));
  }
  SetVector(y, 1, RememberSimple_(DYNX(W_,101), 1));
  SetVector(y, 2, RememberSimple_(DYNX(W_,100), 2));
  SolveLinearSystemOfEquations(J, b, y, 2);
  DYNX(W_,101) = GetVector(y, 1);
  DYNX(W_,100) = GetVector(y, 2);
  EndStaticLinearSystemOfEquations(J);
}
 /* End of Equation Block */ 

DYNX(W_,98) = DYNX(X_,13)-DYNX(DP_,34)*DYNX(W_,100)+DYNX(DP_,41)*DYNX(W_,101);
DYNX(W_,99) = DYNX(X_,12)-(DYNX(DP_,34)*DYNX(W_,101)+DYNX(DP_,40)*DYNX(W_,100));
DYNX(W_,0) = DYNX(W_,107)*(DYNX(DYNhelp,78)*DYNX(W_,98)+DYNX(DYNhelp,76)*
  DYNX(W_,99));
DYNX(W_,1) = DYNX(W_,107)*(DYNX(DYNhelp,78)*DYNX(W_,99)-DYNX(DYNhelp,76)*
  DYNX(W_,98));
DYNX(W_,4) = sqrtGuarded(sqr(DYNX(W_,0))+sqr(DYNX(W_,1)),"pwPin.vr^2+pwPin.vi^2");
DYNX(F_,2) = divmacro(DYNX(DP_,21)*DYNX(W_,4)-DYNX(X_,2),"avr2.firstOrder2.k*avr2.v-avr2.firstOrder2.y",
  DYNX(W_,39),"avr2.firstOrder2.T");
DYNX(F_,11) = divmacro((DYNX(DP_,38)-DYNX(DP_,39)-divmacro(divmacro(DYNX(DP_,45)
  *DYNX(DP_,41)*(DYNX(DP_,38)-DYNX(DP_,39)),"order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)",
  DYNX(DP_,43),"order6_1.T1q0"),"order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)/order6_1.T1q0",
  DYNX(DP_,39),"order6_1.x1q"))*DYNX(W_,101)-DYNX(X_,11),"(order6_1.xq-order6_1.x1q-order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)/order6_1.T1q0/order6_1.x1q)*order6_1.iq-order6_1.e1d",
  DYNX(DP_,43),"order6_1.T1q0");
DYNX(F_,13) = divmacro(DYNX(X_,11)-DYNX(X_,13)+(DYNX(DP_,39)-DYNX(DP_,41)+
  divmacro(divmacro(DYNX(DP_,45)*DYNX(DP_,41)*(DYNX(DP_,38)-DYNX(DP_,39)),
  "order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)",DYNX(DP_,43),
  "order6_1.T1q0"),"order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)/order6_1.T1q0",
  DYNX(DP_,39),"order6_1.x1q"))*DYNX(W_,101),"order6_1.e1d-order6_1.e2d+(order6_1.x1q-order6_1.x2q+order6_1.T2q0*order6_1.x2q*(order6_1.xq-order6_1.x1q)/order6_1.T1q0/order6_1.x1q)*order6_1.iq",
  DYNX(DP_,45),"order6_1.T2q0");
DYNX(W_,103) = divmacro(DYNX(W_,5)*DYNX(W_,83),"avr2.vf*order6_1.V_b",
  DYNX(W_,91),"order6_1.Vn");
DYNX(F_,10) = divmacro((1-divmacro(DYNX(DP_,46),"order6_1.Taa",DYNX(DP_,42),
  "order6_1.T1d0"))*DYNX(W_,103)-(DYNX(X_,10)+(DYNX(DP_,37)-DYNX(DP_,35)-
  divmacro(divmacro(DYNX(DP_,44)*DYNX(DP_,40)*(DYNX(DP_,37)-DYNX(DP_,35)),
  "order6_1.T2d0*order6_1.x2d*(order6_1.xd-order6_1.x1d)",DYNX(DP_,42),
  "order6_1.T1d0"),"order6_1.T2d0*order6_1.x2d*(order6_1.xd-order6_1.x1d)/order6_1.T1d0",
  DYNX(DP_,35),"order6_1.x1d"))*DYNX(W_,100)),"(1-order6_1.Taa/order6_1.T1d0)*order6_1.vf_MB-(order6_1.e1q+(order6_1.xd-order6_1.x1d-order6_1.T2d0*order6_1.x2d*(order6_1.xd-order6_1.x1d)/order6_1.T1d0/order6_1.x1d)*order6_1.id)",
  DYNX(DP_,42),"order6_1.T1d0");
DYNX(F_,12) = divmacro(DYNX(X_,10)-DYNX(X_,12)-(DYNX(DP_,35)-DYNX(DP_,40)+
  divmacro(divmacro(DYNX(DP_,44)*DYNX(DP_,40)*(DYNX(DP_,37)-DYNX(DP_,35)),
  "order6_1.T2d0*order6_1.x2d*(order6_1.xd-order6_1.x1d)",DYNX(DP_,42),
  "order6_1.T1d0"),"order6_1.T2d0*order6_1.x2d*(order6_1.xd-order6_1.x1d)/order6_1.T1d0",
  DYNX(DP_,35),"order6_1.x1d"))*DYNX(W_,100)+divmacro(DYNX(DP_,46)*DYNX(W_,103),
  "order6_1.Taa*order6_1.vf_MB",DYNX(DP_,42),"order6_1.T1d0"),"order6_1.e1q-order6_1.e2q-(order6_1.x1d-order6_1.x2d+order6_1.T2d0*order6_1.x2d*(order6_1.xd-order6_1.x1d)/order6_1.T1d0/order6_1.x1d)*order6_1.id+order6_1.Taa*order6_1.vf_MB/order6_1.T1d0",
  DYNX(DP_,44),"order6_1.T2d0");
DYNX(W_,81) = DYNX(W_,73)+divmacro(DYNX(DP_,27)-DYNX(X_,9),"tGTypeI.wref-order6_1.w",
  DYNX(DP_,28),"tGTypeI.R");
DYNX(W_,76) = IF GreaterEqual(DYNX(W_,81),"tGTypeI.pinstar", 0,"0", 0) AND 
  LessEqual(DYNX(W_,81),"tGTypeI.pinstar", 1,"1", 1) THEN DYNX(W_,81) ELSE IF 
  Greater(DYNX(W_,81),"tGTypeI.pinstar", 1,"1", 2) THEN 1 ELSE 0;
DYNX(F_,5) = divmacro(DYNX(W_,76)-DYNX(X_,5),"tGTypeI.pin-tGTypeI.xg1",
  DYNX(DP_,29),"tGTypeI.Ts");
DYNX(F_,6) = divmacro((1-divmacro(DYNX(DP_,31),"tGTypeI.T3",DYNX(DP_,30),
  "tGTypeI.Tc"))*DYNX(X_,5)-DYNX(X_,6),"(1-tGTypeI.T3/tGTypeI.Tc)*tGTypeI.xg1-tGTypeI.xg2",
  DYNX(DP_,30),"tGTypeI.Tc");
DYNX(F_,7) = divmacro((1-divmacro(DYNX(DP_,32),"tGTypeI.T4",DYNX(DP_,33),
  "tGTypeI.T5"))*(DYNX(X_,6)+divmacro(DYNX(DP_,31)*DYNX(X_,5),"tGTypeI.T3*tGTypeI.xg1",
  DYNX(DP_,30),"tGTypeI.Tc"))-DYNX(X_,7),"(1-tGTypeI.T4/tGTypeI.T5)*(tGTypeI.xg2+tGTypeI.T3*tGTypeI.xg1/tGTypeI.Tc)-tGTypeI.xg3",
  DYNX(DP_,33),"tGTypeI.T5");
DYNX(W_,72) = DYNX(X_,7)+divmacro((DYNX(X_,6)+divmacro(DYNX(DP_,31)*DYNX(X_,5),
  "tGTypeI.T3*tGTypeI.xg1",DYNX(DP_,30),"tGTypeI.Tc"))*DYNX(DP_,32),
  "(tGTypeI.xg2+tGTypeI.T3*tGTypeI.xg1/tGTypeI.Tc)*tGTypeI.T4",DYNX(DP_,33),
  "tGTypeI.T5");
DYNX(W_,102) = (DYNX(W_,99)+DYNX(DP_,34)*DYNX(W_,101))*DYNX(W_,101)+(DYNX(W_,98)
  +DYNX(DP_,34)*DYNX(W_,100))*DYNX(W_,100);
DYNX(F_,9) = divmacro(DYNX(W_,72)*DYNX(W_,105)-DYNX(W_,102),"tGTypeI.pm*order6_1.S_SBtoMB-order6_1.pe",
  DYNX(DP_,36),"order6_1.M");
DYNX(F_,8) = DYNX(W_,104)*(DYNX(X_,9)-1);
DYNX(W_,53) = sqrtGuarded(sqr(DYNX(W_,4)),"avr2.v^2");
DYNX(W_,65) = DYNX(W_,53)-DYNX(W_,66);
DYNX(F_,4) = IF DYNX(X_,4) < DYNX(DP_,25) AND DYNX(W_,67)*DYNX(W_,65) < 0 OR 
  DYNX(X_,4) > DYNX(W_,68) AND DYNX(W_,67)*DYNX(W_,65) > 0 THEN 0 ELSE 
  DYNX(W_,67)*DYNX(W_,65);
if (NewParameters_) {
DYNX(DYNhelp,80) = fabs(DYNX(W_,44));
}
DYNX(W_,14) = IF DYNX(DYNhelp,80) <= 1E-15 THEN RealBmax(RealBmin(DYNX(W_,42)*
  DYNX(W_,43), DYNX(W_,46)), DYNX(W_,47)) ELSE RealBmax(RealBmin(DYNX(X_,3), 
  DYNX(W_,46)), DYNX(W_,47));
DYNX(DYNhelp,81) = fabs(DYNX(W_,5));
DYNX(DYNhelp,82) = exp(DYNX(W_,31)*DYNX(DYNhelp,81));
DYNX(W_,15) = DYNX(W_,30)*DYNX(DYNhelp,82)*DYNX(W_,5);
DYNX(W_,16) = DYNX(W_,14)-DYNX(W_,15);
DYNX(F_,0) = divmacro(DYNX(W_,29)*DYNX(W_,16)-DYNX(W_,18)*DYNX(X_,0),
  "avr2.ExcitationSystem.a_end*avr2.feedback.y-avr2.ExcitationSystem.a[2]*avr2.ExcitationSystem.x_scaled[1]",
  DYNX(W_,17),"avr2.ExcitationSystem.a[1]");
DYNX(F_,1) = IF DYNX(W_,37) THEN 0 ELSE divmacro(DYNX(W_,5)-DYNX(X_,1),
  "avr2.vf-avr2.derivativeBlock.x",DYNX(W_,33),"avr2.derivativeBlock.T");
  beginwhenBlock
  whenModelica(GreaterMinor(DYNX(X_,3),"avr2.simpleLagLim.state", DYNX(W_,46),
    "avr2.simpleLagLim.outMax", 3) AND LessMinor(DYNX(W_,43)*DYNX(W_,42)-
    DYNX(X_,3),"avr2.simpleLagLim.K*avr2.simpleLagLim.u-avr2.simpleLagLim.state",
     0,"0", 4), 0) 
    reinit(DYNX(X_,3), DYNX(W_,46));
  endwhenModelica()

  whenModelica(LessMinor(DYNX(X_,3),"avr2.simpleLagLim.state", DYNX(W_,47),
    "avr2.simpleLagLim.outMin", 5) AND GreaterMinor(DYNX(W_,43)*DYNX(W_,42)-
    DYNX(X_,3),"avr2.simpleLagLim.K*avr2.simpleLagLim.u-avr2.simpleLagLim.state",
     0,"0", 6), 1) 
    reinit(DYNX(X_,3), DYNX(W_,47));
  endwhenModelica()
  endwhenBlock


AcceptedSection1

AcceptedSection2
DYNX(W_,22) = divmacro(DYNX(X_,0),"avr2.ExcitationSystem.x_scaled[1]",
  DYNX(W_,29),"avr2.ExcitationSystem.a_end");
DYNX(W_,97) = atan2(DYNX(W_,1), DYNX(W_,0));

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("SysData.S_b", "System base [MVA]", 0, 750, 0.0,0.0,0.0,0,560)
DeclareParameter("SysData.fn", "System Frequency [Hz]", 1, 50, 0.0,0.0,0.0,0,560)
DeclareVariable("pwPin.vr", "Real part of the voltage [1]", 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("pwPin.vi", "Imaginary part of the voltage [1]", 0.0, 0.0,0.0,\
0.0,0,520)
DeclareVariable("pwPin.ir", "Real part of the current [1]", 0.0, 0.0,0.0,0.0,0,777)
DeclareVariable("pwPin.ii", "Imaginary part of the current [1]", 0.0, 0.0,0.0,\
0.0,0,777)
DeclareParameter("V_b", "Base voltage of the bus [kV]", 2, 400, 0.0,0.0,0.0,0,560)
DeclareParameter("V_0", "Voltage magnitude (pu) [1]", 3, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("angle_0", "Voltage angle [deg]", 4, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("P_0", "Active power [MW]", 5, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("Q_0", "Reactive power [Mvar]", 6, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("M_b", "Machine base power (MVA) [MVA]", 7, 460, 0.0,0.0,0.0,0,560)
DeclareVariable("avr2.v", "Generator termminal voltage (pu) [1]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("avr2.vf", "Filed voltage (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("avr2.vref", "Reference generator terminal voltage (pu) [1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("avr2.vrmin", "Minimum regulator voltage (pu) [1]", 8, -5, \
0.0,0.0,0.0,0,560)
DeclareParameter("avr2.vrmax", "Maximum regulator voltage (pu) [1]", 9, 5, \
0.0,0.0,0.0,0,560)
DeclareParameter("avr2.Ka", "Amplifier gain (pu/pu) [s]", 10, 400, 0.0,0.0,0.0,0,560)
DeclareParameter("avr2.Ta", "Amplifier time constant (s) [s]", 11, 0.2, 0.0,0.0,\
0.0,0,560)
DeclareParameter("avr2.Kf", "Stabilizer gain (pu/pu) [1]", 12, 0.01, 0.0,0.0,0.0,\
0,560)
DeclareParameter("avr2.Tf", "Stabilizer time constant (s) [s]", 13, 0.0005, \
0.0,0.0,0.0,0,560)
DeclareParameter("avr2.Ke", "Field circuit integral deviation (pu/pu)", 14, 1, \
0.0,0.0,0.0,0,560)
DeclareParameter("avr2.Te", "Field circuit time constant (s) [s]", 15, 0.0001, \
0.0,0.0,0.0,0,560)
DeclareParameter("avr2.Tr", "Measurement time constant (s) [s]", 16, 0.01, \
0.0,0.0,0.0,0,560)
DeclareParameter("avr2.Ae", "1st ceiling coefficient", 17, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("avr2.Be", "2nd ceiling coefficient", 18, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("avr2.v0", "Initial measured voltage [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("avr2.vfstate", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("avr2.vf00", "Initialization of vf [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("avr2.vr10", "Initialization [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("avr2.vr20", "Initialization [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("avr2.vref0", "Voltage reference at t=0 (pu) [1]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("avr2.vf0", "Reference generator terminal voltage (pu) [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("avr2.feedback.u1", "[1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("avr2.feedback.u2", "[1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("avr2.feedback.y", "[1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("avr2.ExcitationSystem.u", "Connector of Real input signal [1]", \
"avr2.feedback.y", 1, 5, 16, 0)
DeclareAlias2("avr2.ExcitationSystem.y", "Connector of Real output signal [1]", \
"avr2.vf", 1, 5, 5, 0)
DeclareParameter("avr2.ExcitationSystem.b[1]", "Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 19, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("avr2.ExcitationSystem.a[1]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6}) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("avr2.ExcitationSystem.a[2]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6}) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("avr2.ExcitationSystem.initType", "Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareVariable("avr2.ExcitationSystem.x_start[1]", "Initial or guess values of states [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("avr2.ExcitationSystem.y_start", "Initial value of output (derivatives of y are zero up to nx-1-th derivative) [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("avr2.ExcitationSystem.x[1]", "State of transfer function from controller canonical form [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("avr2.ExcitationSystem.na", "Size of Denominator of transfer function. [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("avr2.ExcitationSystem.nb", "Size of Numerator of transfer function. [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("avr2.ExcitationSystem.nx", "[:#(type=Integer)]", 1, 0.0,0.0,0.0,\
0,2565)
DeclareVariable("avr2.ExcitationSystem.bb[1]", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("avr2.ExcitationSystem.bb[2]", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("avr2.ExcitationSystem.d", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("avr2.ExcitationSystem.a_end", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareState("avr2.ExcitationSystem.x_scaled[1]", "Scaled vector x", 0, 0.0, \
0.0,0.0,0.0,0,2592)
DeclareDerivative("avr2.ExcitationSystem.der(x_scaled[1])", "der(Scaled vector x)",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("avr2.ceilingBlock.u", "Connector of Real input signal [1]", \
"avr2.vf", 1, 5, 5, 0)
DeclareAlias2("avr2.ceilingBlock.y", "Connector of Real output signal [1]", \
"avr2.feedback.u2", 1, 5, 15, 0)
DeclareVariable("avr2.ceilingBlock.Ae", "First ceiling coefficient", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("avr2.ceilingBlock.Be", "Second ceiling coefficient", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("avr2.derivativeBlock.k", "Gains [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("avr2.derivativeBlock.T", "Time constants (T>0 required; T=0 is ideal derivative block) [s]",\
 1E-60, 1E-60,1E+100,0.0,0,513)
DeclareVariable("avr2.derivativeBlock.initType", "Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("avr2.derivativeBlock.x_start", "Initial or guess value of state [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("avr2.derivativeBlock.y_start", "Initial value of output (= state) [s-1]",\
 20, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("avr2.derivativeBlock.u", "Connector of Real input signal [1]", \
"avr2.vf", 1, 5, 5, 0)
DeclareVariable("avr2.derivativeBlock.y", "Connector of Real output signal [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("avr2.derivativeBlock.x", "State of block [1]", 1, 0.0, 0.0,0.0,0.0,\
0,544)
DeclareDerivative("avr2.derivativeBlock.der(x)", "der(State of block) [s-1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("avr2.derivativeBlock.zeroGain", "[:#(type=Boolean)]", false, \
0.0,0.0,0.0,0,2563)
DeclareVariable("avr2.feedback1.u1", "[s-1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("avr2.feedback1.u2", "[s-1]", "avr2.derivativeBlock.y", 1, 5, 36, 0)
DeclareAlias2("avr2.feedback1.y", "[s-1]", "avr2.simpleLagLim.u", 1, 5, 42, 0)
DeclareParameter("avr2.firstOrder2.k", "Gain [1]", 21, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("avr2.firstOrder2.T", "Time Constant [s]", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("avr2.firstOrder2.initType", "Type of initialization (1: no init, 2: steady state, 3/4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("avr2.firstOrder2.y_start", "Initial or guess value of output (= state) [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("avr2.firstOrder2.u", "Connector of Real input signal [1]", \
"avr2.v", 1, 5, 4, 0)
DeclareState("avr2.firstOrder2.y", "Connector of Real output signal [1]", 2, 0.0,\
 0.0,0.0,0.0,0,544)
DeclareDerivative("avr2.firstOrder2.der(y)", "der(Connector of Real output signal) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("avr2.Verr.u1", "[1]", "avr2.vref", 1, 5, 6, 0)
DeclareAlias2("avr2.Verr.u2", "[1]", "avr2.firstOrder2.y", 1, 1, 2, 0)
DeclareAlias2("avr2.Verr.y", "[1]", "avr2.feedback1.u1", 1, 5, 38, 0)
DeclareVariable("avr2.simpleLagLim.u", "Connector of Real input signal [s-1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("avr2.simpleLagLim.y", "Connector of Real output signal [1]", \
"avr2.feedback.u1", 1, 5, 14, 0)
DeclareAlias2("avr2.simpleLagLim.const.y", "Value of Real output [s]", \
"avr2.simpleLagLim.T", 1, 5, 44, 0)
DeclareState("avr2.simpleLagLim.state", "[1]", 3, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("avr2.simpleLagLim.der(state)", "[s-1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("avr2.simpleLagLim.K", "Gain [s]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("avr2.simpleLagLim.T", "Lag time constant [s]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("avr2.simpleLagLim.y_start", "Output start value [1]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("avr2.simpleLagLim.outMax", "Maximum output value [1]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("avr2.simpleLagLim.outMin", "Minimum output value [1]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("avr2.simpleLagLim.T_mod", "[s]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareAlias2("oel.v", "Generator terminal voltage (pu) [1]", "avr2.v", 1, 5, 4,\
 0)
DeclareVariable("oel.p", "Active power (pu) [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("oel.q", "Reactive power (pu) [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("oel.field_current.v", "generator terminal voltage (pu) [1]", \
"avr2.v", 1, 5, 4, 0)
DeclareVariable("oel.field_current.p", "active power (pu) [1]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("oel.field_current.q", "reactive power (pu) [1]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("oel.field_current.ifield", "estimated field current (pu) [1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("oel.field_current.xd", "[1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("oel.field_current.xq", "[1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("oel.field_current.gamma_p", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("oel.field_current.gamma_q", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareAlias2("oel.v_ref", "[1]", "avr2.vref", 1, 5, 6, 0)
DeclareParameter("oel.T0", "Integrator time constant (s) [s]", 22, 10, 0.0,0.0,\
0.0,0,560)
DeclareVariable("oel.xd", "d-axis estimated generator reactance (pu, machine base) [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("oel.xq", "q-axis estimated generator reactance (pu, machine base) [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("oel.if_lim", "Maximum field current (pu, system base) [1]", 23,\
 2.825, 0.0,0.0,0.0,0,560)
DeclareParameter("oel.vOEL_max", "Maximum output signal (pu, machine base) [1]",\
 24, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("oel.Sn", "Power rating (MVA) [MVA]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("oel.Vn", "Voltage rating (kV) [kV]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("oel.V_b", "Base voltage of the bus (kV) [kV]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("oel.Z_MBtoSB", "Z(machine base) -> Z(system base) [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("oel.I_MBtoSB", "I(machine base) -> I(system base) [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareAlias2("oel.add.u1", "[1]", "oel.field_current.ifield", 1, 5, 53, 0)
DeclareAlias2("oel.add.u2", "[1]", "oel.currentLimit.k", 1, 5, 66, 0)
DeclareVariable("oel.add.y", "[1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("oel.currentLimit.k", "Constant output value [1]", 1, 0.0,0.0,\
0.0,0,513)
DeclareAlias2("oel.currentLimit.y", "Connector of Real output signal [1]", \
"oel.currentLimit.k", 1, 5, 66, 0)
DeclareVariable("oel.limIntegrator.k", "Integrator gain [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("oel.limIntegrator.outMax", "Upper limit of output [1]", 1, \
0.0,0.0,0.0,0,513)
DeclareParameter("oel.limIntegrator.outMin", "Lower limit of output", 25, 0, \
0.0,0.0,0.0,0,560)
DeclareVariable("oel.limIntegrator.initType", "Type of initialization (1: no init, 2: steady state, 3/4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 3, 1.0,4.0,0.0,0,517)
DeclareVariable("oel.limIntegrator.limitsAtInit", "= false, if limits are ignored during initialization (i.e., der(y)=k*u) [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareParameter("oel.limIntegrator.y_start", "Initial or guess value of output (must be in the limits outMin .. outMax) [1]",\
 26, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("oel.limIntegrator.strict", "= true, if strict limits with noEvent(..) [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareAlias2("oel.limIntegrator.u", "Connector of Real input signal [1]", \
"oel.add.y", 1, 5, 65, 0)
DeclareState("oel.limIntegrator.y", "Connector of Real output signal [1]", 4, \
0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("oel.limIntegrator.der(y)", "der(Connector of Real output signal) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("oel.v_ref0", "Generator terminal voltage (pu) [1]", "avr2.vref0", 1,\
 5, 12, 0)
DeclareAlias2("oel.difference.u1", "[1]", "avr2.vref0", 1, 5, 12, 0)
DeclareAlias2("oel.difference.u2", "[1]", "oel.limIntegrator.y", 1, 1, 4, 0)
DeclareAlias2("oel.difference.y", "[1]", "avr2.vref", 1, 5, 6, 0)
DeclareAlias2("tGTypeI.w", "Rotor speed (pu) [1]", "order6_1.w", 1, 1, 9, 0)
DeclareVariable("tGTypeI.pm", "Mechanical power (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("tGTypeI.wref", "Speed reference (pu) [1]", 27, 1, 0.0,0.0,0.0,\
0,560)
DeclareVariable("tGTypeI.pref", "Active power reference (pu) [1]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareParameter("tGTypeI.R", "Droop (pu)", 28, 0.04, 0.0,0.0,0.0,0,560)
DeclareVariable("tGTypeI.pmax", "Maximum turbine output (pu) [1]", 1, 0.0,0.0,\
0.0,0,513)
DeclareVariable("tGTypeI.pmin", "Minimum turbine output (pu) [1]", 0, 0.0,0.0,\
0.0,0,513)
DeclareParameter("tGTypeI.Ts", "Governor time constant (s)", 29, 0.1, 0.0,0.0,\
0.0,0,560)
DeclareParameter("tGTypeI.Tc", "Servo time constant (s)", 30, 0.4, 0.0,0.0,0.0,0,560)
DeclareParameter("tGTypeI.T3", "Transient gain time constant (s)", 31, 0, \
0.0,0.0,0.0,0,560)
DeclareParameter("tGTypeI.T4", "Power fraction time constant (s)", 32, 2.33, \
0.0,0.0,0.0,0,560)
DeclareParameter("tGTypeI.T5", "Reheat time constant (s)", 33, 4, 0.0,0.0,0.0,0,560)
DeclareVariable("tGTypeI.pin", "Turbine output (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("tGTypeI.pin0", "Initialization [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("tGTypeI.xg10", "Initialization [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("tGTypeI.xg20", "Initialization", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("tGTypeI.xg30", "Initialization [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("tGTypeI.pinstar", "[1]", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("tGTypeI.xg1", "[1]", 5, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("tGTypeI.der(xg1)", "[s-1]", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("tGTypeI.xg2", "", 6, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("tGTypeI.der(xg2)", "", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("tGTypeI.xg3", "[1]", 7, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("tGTypeI.der(xg3)", "[s-1]", 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("p0", "[1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("order6_1.V_b", "Base voltage of the bus [kV]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("order6_1.V_0", "Voltage magnitude (pu) [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("order6_1.angle_0", "Voltage angle [deg]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("order6_1.P_0", "Active power [MW]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("order6_1.Q_0", "Reactive power [Mvar]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("order6_1.S_b", "System base power [MVA]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("order6_1.fn", "System Frequeny [Hz]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("order6_1.Sn", "Power rating (MVA) [MVA]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("order6_1.Vn", "Voltage rating (kV) [kV]", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("order6_1.ra", "Armature resistance (pu) [1]", 34, 0, 0.0,0.0,\
0.0,0,560)
DeclareParameter("order6_1.x1d", "d-axis transient reactance (pu) [1]", 35, \
1.239130435, 0.0,0.0,0.0,0,560)
DeclareParameter("order6_1.M", "Mechanical starting time (2H), kWs/kVA", 36, \
5.0661, 0.0,0.0,0.0,0,560)
DeclareVariable("order6_1.D", "Damping coefficient", 0, 0.0,0.0,0.0,0,513)
DeclareAlias2("order6_1.p.vr", "Real part of the voltage [1]", "pwPin.vr", 1, 5,\
 0, 4)
DeclareAlias2("order6_1.p.vi", "Imaginary part of the voltage [1]", "pwPin.vi", 1,\
 5, 1, 4)
DeclareVariable("order6_1.p.ir", "Real part of the current [1]", 0.0, 0.0,0.0,\
0.0,0,777)
DeclareVariable("order6_1.p.ii", "Imaginary part of the current [1]", 0.0, \
0.0,0.0,0.0,0,777)
DeclareState("order6_1.delta", "Rotor angle (rad) [rad|rad]", 8, 0.0, 0.0,0.0,\
0.0,0,544)
DeclareDerivative("order6_1.der(delta)", "der(Rotor angle (rad)) [rad/s]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("order6_1.w", "Rotor speed (pu) [1]", 9, 1, 0.0,0.0,0.0,0,544)
DeclareDerivative("order6_1.der(w)", "der(Rotor speed (pu)) [s-1]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("order6_1.v", "Generator terminal voltage (pu) [1]", "avr2.v", 1, 5,\
 4, 0)
DeclareVariable("order6_1.P", "Active power (pu) [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("order6_1.Q", "Reactive power (pu) [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("order6_1.vf", "Field voltage (pu) [1]", "avr2.vf", 1, 5, 5, 0)
DeclareAlias2("order6_1.vf0", "Initial field voltage (pu) [1]", "order6_1.vf00", 1,\
 5, 138, 0)
DeclareAlias2("order6_1.pm0", "Initial mechanical power (pu) [1]", \
"order6_1.pm00", 1, 5, 131, 0)
DeclareAlias2("order6_1.pm", "Mechanical power (pu) [1]", "tGTypeI.pm", 1, 5, 72,\
 0)
DeclareVariable("order6_1.anglev", " Bus voltage angle (rad) [rad|deg]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("order6_1.vd", "d-axis voltage (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("order6_1.vq", "q-axis voltage (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("order6_1.id", "d-axis currrent (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("order6_1.iq", "q-axis current (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("order6_1.pe", "electrical power transmitted through the air-gap [1]",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("order6_1.vf_MB", "field voltage on machine base [1]", 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("order6_1.w_b", "Base frequency in rad/s [rad/s]", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("order6_1.S_SBtoMB", "S(system base) -> S(machine base) [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.I_MBtoSB", "I(machine base) -> I(system base) [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.V_MBtoSB", "V(machine base) -> V(system base) [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.Z_MBtoSB", "Z(machine base) -> Z(system base) [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.p0", "Initial active power generation in pu (system base) [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.q0", "Initial reactive power generation in pu (system base) [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.Vt0.re", "Real part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("order6_1.Vt0.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.S0.re", "Real part of complex number [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.S0.im", "Imaginary part of complex number [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.I0.re", "Real part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("order6_1.I0.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.vr0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.vi0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.ir0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.ii0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.xq0", "used for setting the initial rotor angle [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.delta0", "Init. val. rotor angle [rad|deg]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.Vdq0.re", "Real part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("order6_1.Vdq0.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.Idq0.re", "Real part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("order6_1.Idq0.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.vd0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.vq0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.id0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.iq0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.pm00", "Init. val. (pu, system base) [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareParameter("order6_1.xd", "d-axis synchronous reactance (pu) [1]", 37, \
4.076086957, 0.0,0.0,0.0,0,560)
DeclareParameter("order6_1.xq", "q-axis synchronous reactance (pu) [1]", 38, \
2.690217391, 0.0,0.0,0.0,0,560)
DeclareParameter("order6_1.x1q", "q-axis transient reactance (pu) [1]", 39, 0.5,\
 0.0,0.0,0.0,0,560)
DeclareParameter("order6_1.x2d", "d-axis sub-transient reactance (pu) [1]", 40, \
1.010869565, 0.0,0.0,0.0,0,560)
DeclareParameter("order6_1.x2q", "q-axis sub-transient reactance (pu) [1]", 41, \
0.945651739, 0.0,0.0,0.0,0,560)
DeclareParameter("order6_1.T1d0", "d-axis open circuit transient time constant (s)",\
 42, 3.066666666, 0.0,0.0,0.0,0,560)
DeclareParameter("order6_1.T1q0", "q-axis open circuit transient time constant (s)",\
 43, 2, 0.0,0.0,0.0,0,560)
DeclareParameter("order6_1.T2d0", "d-axis open circuit sub-transient time constant (s)",\
 44, 0.0429333, 0.0,0.0,0.0,0,560)
DeclareParameter("order6_1.T2q0", "q-axis open circuit sub-transient time constant (s)",\
 45, 0.0552, 0.0,0.0,0.0,0,560)
DeclareParameter("order6_1.Taa", "d-axis aditional leakage time constant (s)", 46,\
 0.00122666, 0.0,0.0,0.0,0,560)
DeclareState("order6_1.e1q", "q-axis transient voltage [1]", 10, 0.0, 0.0,0.0,\
0.0,0,544)
DeclareDerivative("order6_1.der(e1q)", "der(q-axis transient voltage) [s-1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareState("order6_1.e1d", "d-axis transient voltage [1]", 11, 0.0, 0.0,0.0,\
0.0,0,544)
DeclareDerivative("order6_1.der(e1d)", "der(d-axis transient voltage) [s-1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareState("order6_1.e2q", "q-axis sub-transient voltage [1]", 12, 0.0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("order6_1.der(e2q)", "der(q-axis sub-transient voltage) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("order6_1.e2d", "d-axis sub-transient voltage [1]", 13, 0.0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("order6_1.der(e2d)", "der(d-axis sub-transient voltage) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("order6_1.e2q0", "Initialitation [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.e2d0", "Initialitation [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.e1d0", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.K1", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.K2", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.e1q0", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("order6_1.vf00", "Init. val. (pu, SB) [1]", 0.0, 0.0,0.0,0.0,0,2561)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(F_,3), 0.0, 0);
DoRemember_(DYNX(W_,100), DYNX(W_,129), 2);
DoRemember_(DYNX(W_,101), DYNX(W_,130), 1);
EndEqBlock
UpdateQEvaluate(2)
EndDataBlock

BreakSectionFunctionStart(0);
BreakSectionFunctionCallNew(1);
BreakSectionFunctionEnd()
